export interface SecretPattern {
  id: string; name: string; regex: RegExp;
  severity: "critical" | "high" | "medium" | "low";
  entropy_threshold?: number; description: string;
}

export const PATTERNS: SecretPattern[] = [
  { id:"anthropic_key",    severity:"critical", name:"Anthropic API Key",
    regex:/\bsk-ant-[a-zA-Z0-9\-_]{90,}\b/g,
    description:"Anthropic Claude API key — full account access" },
  { id:"openai_key",       severity:"critical", name:"OpenAI API Key",
    regex:/\bsk-[a-zA-Z0-9]{48}\b/g,
    description:"OpenAI API key — full billing access" },
  { id:"github_token",     severity:"critical", name:"GitHub Personal Access Token",
    regex:/\bghp_[a-zA-Z0-9]{36}\b/g,
    description:"GitHub PAT — repo read/write access" },
  { id:"github_oauth",     severity:"critical", name:"GitHub OAuth Token",
    regex:/\bgho_[a-zA-Z0-9]{36}\b/g,
    description:"GitHub OAuth token" },
  { id:"aws_access_key",   severity:"critical", name:"AWS Access Key",
    regex:/\bAKIA[A-Z0-9]{16}\b/g,
    description:"AWS access key ID — cloud resource access" },
  { id:"aws_secret",       severity:"critical", name:"AWS Secret Key",
    regex:/(?<![a-zA-Z0-9])([a-zA-Z0-9\/+=]{40})(?![a-zA-Z0-9])/g,
    entropy_threshold: 4.5,
    description:"Probable AWS secret access key (high entropy)" },
  { id:"google_api_key",   severity:"high",     name:"Google API Key",
    regex:/\bAIza[a-zA-Z0-9\-_]{35}\b/g,
    description:"Google API key — Maps, Firebase, etc." },
  { id:"stripe_secret",    severity:"critical", name:"Stripe Secret Key",
    regex:/\bsk_live_[a-zA-Z0-9]{24,}\b/g,
    description:"Stripe live secret key — payment processing" },
  { id:"stripe_restricted",severity:"high",     name:"Stripe Restricted Key",
    regex:/\brk_live_[a-zA-Z0-9]{24,}\b/g,
    description:"Stripe restricted key" },
  { id:"jwt_secret",       severity:"high",     name:"JWT Secret (hardcoded)",
    regex:/(?:jwt[_\-\s]?secret|jwt[_\-\s]?key)\s*[:=]\s*["']([^"']{16,})["']/gi,
    description:"Hardcoded JWT signing secret" },
  { id:"db_url_password",  severity:"high",     name:"Database URL with credentials",
    regex:/(?:postgres|mysql|mongodb|redis):\/\/[^:]+:([^@]{8,})@/gi,
    description:"Database connection string with embedded password" },
  { id:"private_key",      severity:"critical", name:"Private Key (PEM)",
    regex:/-----BEGIN (?:RSA |EC )?PRIVATE KEY-----/g,
    description:"Private key in PEM format" },
  { id:"sendgrid_key",     severity:"high",     name:"SendGrid API Key",
    regex:/\bSG\.[a-zA-Z0-9\-_]{22}\.[a-zA-Z0-9\-_]{43}\b/g,
    description:"SendGrid email API key" },
  { id:"slack_token",      severity:"high",     name:"Slack Token",
    regex:/\bxox[baprs]-[0-9a-zA-Z\-]{10,}\b/g,
    description:"Slack bot or user token" },
  { id:"npm_token",        severity:"high",     name:"npm Access Token",
    regex:/\bnpm_[a-zA-Z0-9]{36}\b/g,
    description:"npm registry access token" },
  { id:"klaviyo_key",      severity:"high",     name:"Klaviyo API Key",
    regex:/\bpk_[a-zA-Z0-9]{32,}\b/g,
    description:"Klaviyo public/private API key" },
  { id:"shopify_token",    severity:"critical", name:"Shopify Access Token",
    regex:/\bshpat_[a-fA-F0-9]{32}\b/g,
    description:"Shopify Admin API access token — full store access" },
  { id:"generic_secret",   severity:"medium",   name:"Generic Secret Assignment",
    regex:/(?:secret|password|passwd|api_key|apikey|auth_token|access_token)\s*[:=]\s*["']([^"'\s]{12,})["']/gi,
    entropy_threshold: 3.5,
    description:"Generic secret-like string assignment" },
];
